# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.FileField(upload_to=b'', verbose_name=b'company logo')),
            ],
        ),
        migrations.CreateModel(
            name='Hiree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateTimeField(verbose_name=b'date of birth')),
                ('face_picture', models.FileField(upload_to=b'', verbose_name=b'face')),
                ('resume_picture', models.FileField(upload_to=b'', verbose_name=b'resume')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CareerTinder.Company')),
            ],
        ),
    ]
