# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 05:52
from __future__ import unicode_literals

import CareerTinder.listfield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerTinder', '0003_auto_20160918_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='hirees',
            field=CareerTinder.listfield.ListField(default=b''),
        ),
        migrations.AlterField(
            model_name='hiree',
            name='degree',
            field=models.CharField(choices=[(b'BA', b'B.A./B.S.'), (b'MA', b'M.A./M.S.'), (b'DO', b'Ph.D. or Higher')], max_length=1),
        ),
    ]
