# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerTinder', '0003_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='relations',
            name='encounter_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
