# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerTinder', '0004_relations_encounter_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='relations',
            name='status',
            field=models.CharField(choices=[(b'0', b'Undecided'), (b'1', b'Rejected'), (b'2', b'Accepted')], default='0', max_length=20),
            preserve_default=False,
        ),
    ]
