# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 08:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerTinder', '0006_auto_20160918_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='relations',
            name='encounter_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 18, 4, 34, 43, 500000)),
        ),
        migrations.AddField(
            model_name='relations',
            name='status',
            field=models.CharField(choices=[(b'0', b'Undecided'), (b'1', b'Rejected'), (b'2', b'Accepted')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
