# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CareerTinder', '0005_relations_status'),
        ('CareerTinder', '0006_auto_20160918_0224'),
    ]

    operations = [
    ]
