# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 06:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerTinder', '0007_merge_20160918_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relations',
            name='encounter_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 18, 2, 48, 6, 679982)),
        ),
    ]
