# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 07:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerTinder', '0010_auto_20160918_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiree',
            name='name',
        ),
        migrations.AddField(
            model_name='hiree',
            name='first_name',
            field=models.CharField(default='Yo', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hiree',
            name='last_name',
            field=models.CharField(default='Suh', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relations',
            name='encounter_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 18, 3, 5, 14, 369264)),
        ),
    ]
