# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerTinder', '0011_auto_20160918_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiree',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='hiree',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='relations',
            name='encounter_date',
        ),
        migrations.RemoveField(
            model_name='relations',
            name='status',
        ),
        migrations.AddField(
            model_name='hiree',
            name='name',
            field=models.CharField(default='Yo', max_length=50),
            preserve_default=False,
        ),
    ]
