# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 07:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CareerTinder', '0012_auto_20160918_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiree',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='hiree',
            name='last_name',
            field=models.CharField(default='Joeton', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relations',
            name='encounter_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 18, 3, 28, 18, 599735)),
        ),
        migrations.AddField(
            model_name='relations',
            name='status',
            field=models.CharField(choices=[(b'0', b'Undecided'), (b'1', b'Rejected'), (b'2', b'Accepted')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
